In [67]:
import pandas as pd
import numpy as np

In [68]:
data = pd.read_csv('IMDB Dataset.csv')

In [69]:
df = data.iloc[:10000]

In [70]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [71]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [72]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [73]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [74]:
df.duplicated().sum()

np.int64(17)

In [75]:
df.drop_duplicates(inplace=True)

/tmp/ipython-input-3006716147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [76]:
df.duplicated().sum()

np.int64(0)

In [77]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [78]:
df['review'] = df['review'].apply(remove_tags)

/tmp/ipython-input-2336150696.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)


In [79]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [80]:
df['review'] = df['review'].apply(lambda x:x.lower())

/tmp/ipython-input-740760900.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())


In [81]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [82]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

/tmp/ipython-input-2826946130.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [83]:
df

review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [84]:
X = df.iloc[:,0:1]
y = df['sentiment']

In [85]:
X

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [86]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [87]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [88]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [89]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [90]:

X_train.shape

(7986, 1)

In [91]:
!pip install gensim

In [92]:
# using pre-trained model
import gensim
from gensim.models import Word2Vec,KeyedVectors

In [93]:
import kagglehub

path = kagglehub.dataset_download("leadbest/googlenewsvectorsnegative300")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'googlenewsvectorsnegative300' dataset.
Path to dataset files: /kaggle/input/googlenewsvectorsnegative300


In [94]:
model = KeyedVectors.load_word2vec_format('/kaggle/input/googlenewsvectorsnegative300/GoogleNews-vectors-negative300.bin',binary=True,limit=500000)


In [95]:
model['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [96]:
model['cricket'].shape

(300,)

In [101]:
# Remove stopwords

X_train = X_train['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))
# Remove stopwords

X_test = X_test['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [104]:
import spacy
import en_core_web_sm
# Load the spacy model. This takes a few seconds.
nlp = en_core_web_sm.load()
# Process a sentence using the model
doc = nlp(X_train.values[0])
print(doc.vector)

[-0.11225057 -0.3323734  -0.09506241 -0.08899848  0.03331648  0.3578626
  0.24375589  0.25814155  0.20693804 -0.20502327  0.23241748 -0.1819785
 -0.1063184  -0.06482078 -0.10000932  0.20662282 -0.06277418 -0.13001649
  0.25962377 -0.2501759  -0.25346     0.42603675 -0.00766025  0.09086803
  0.07657377  0.09504889  0.14710668  0.2522116   0.16764915  0.17736492
  0.16027842 -0.02066578 -0.06542832  0.00271588 -0.22537896 -0.10483894
 -0.06766807  0.08306239 -0.20810121 -0.1844751  -0.11958811  0.1993304
 -0.17356977  0.06940874  0.11705765  0.21183582 -0.05769423  0.0261329
  0.12440711 -0.0382685  -0.13124184  0.09719379  0.00196476 -0.0585474
 -0.05670151 -0.05204291  0.03033609  0.01203046 -0.06344566  0.07659181
  0.02831528  0.01227162 -0.03398964 -0.33248156 -0.04068003  0.05831385
  0.14982454 -0.08452148 -0.05041636 -0.1549679   0.20063049  0.12990746
 -0.02160156 -0.22049788  0.18294705 -0.00647213 -0.1850161  -0.19923837
  0.08180607 -0.34828505 -0.10278995 -0.02946046 -0.2178

In [107]:
input_arr = []
for item in X_train.values:
    doc = nlp(item)
    input_arr.append(doc.vector)

In [108]:
input_arr = np.array(input_arr)

In [109]:
input_arr.shape

(7986, 96)

In [110]:
input_test_arr = []
for item in X_test.values:
    doc = nlp(item)
    input_test_arr.append(doc.vector)

In [111]:
input_test_arr = np.array(input_test_arr)

In [112]:

input_test_arr.shape

(1997, 96)

In [113]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(input_arr,y_train)

GaussianNB()

In [115]:
y_pred = gnb.predict(input_test_arr)
accuracy_score(y_test,y_pred)

0.6069103655483225

In [114]:
# Building custom word2vec
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

In [48]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [49]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [50]:
story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [51]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [52]:
model.build_vocab(story)

In [53]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(5849986, 6186875)

In [54]:
len(model.wv.index_to_key)

31845

In [56]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [57]:
document_vector(df['review'].values[0])

array([-0.03848681,  0.40127334,  0.17225587, -0.08964925, -0.02929124,
       -0.55075246,  0.15167104,  0.80251086, -0.25431094, -0.08724588,
       -0.05903884, -0.51608044,  0.0731839 ,  0.20207737,  0.04449186,
       -0.23248136,  0.17392571, -0.5500253 , -0.01944769, -0.71128607,
        0.15572576,  0.11564432,  0.30209467, -0.20459847, -0.21466056,
       -0.1967791 , -0.21145058, -0.30676472, -0.358641  ,  0.04779819,
        0.38271385,  0.07826627,  0.08169726, -0.25034836, -0.22279583,
        0.24362066,  0.02558926, -0.3565356 , -0.1659857 , -0.76086944,
        0.17130685, -0.3352058 , -0.16852778,  0.0496421 ,  0.41038784,
       -0.2218777 , -0.3509814 , -0.11381651,  0.18966624,  0.2818842 ,
        0.11182321, -0.24436674, -0.21364081, -0.19045433, -0.47710335,
        0.05967249,  0.33306295,  0.11764307, -0.33833712,  0.06688194,
        0.02426907,  0.16425997, -0.15179628,  0.04429112, -0.39705965,
        0.3584764 , -0.01482662,  0.21937945, -0.63479346,  0.27

In [59]:
df['review'].values

array(["one reviewers mentioned watching 1 oz episode hooked. right, exactly happened me.the first thing struck oz brutality unflinching scenes violence, set right word go. trust me, show faint hearted timid. show pulls punches regards drugs, sex violence. hardcore, classic use word.it called oz nickname given oswald maximum security state penitentary. focuses mainly emerald city, experimental section prison cells glass fronts face inwards, privacy high agenda. em city home many..aryans, muslims, gangstas, latinos, christians, italians, irish more....so scuffles, death stares, dodgy dealings shady agreements never far away.i would say main appeal show due fact goes shows dare. forget pretty pictures painted mainstream audiences, forget charm, forget romance...oz mess around. first episode ever saw struck nasty surreal, say ready it, watched more, developed taste oz, got accustomed high levels graphic violence. violence, injustice (crooked guards who'll sold nickel, inmates who'll kill 

In [58]:
from tqdm import tqdm

In [60]:
X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|██████████| 9983/9983 [08:24<00:00, 19.81it/s]


In [61]:
X = np.array(X)

In [62]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])

In [63]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [64]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [65]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7736604907361042